export const styrelsen = [
  {
    name: "Anton Lind",
    description: "test1",
    role: "Ordförande",
    mail: "ordforande@mforebro.se",
    image: "/styrelsen/Anton-Lind.jpg",
  },
  {
    name: "Cecilia Lai",
    description: "test2",
    role: "Vice ordförande",
    mail: "Vice@mforebro.se",
    image: "/styrelsen/Cecilia-Lai.jpg",
  },
  {
    name: "Wilma Skaro",
    description: "test3",
    role: "Kassör",
    mail: "",
    image: "/styrelsen/Wilma-Skaro.jpg",
  },
  {
    name: "Sofia Stiernström",
    description: "test4",
    role: "Informationsansvarig",
    mail: "info@mforebro.se",
    image: "/styrelsen/Sofia-Stiernström.jpg",
  },
  {
    name: "Erik Lagesson",
    description: "test4",
    role: "Ledamot",
    mail: "ledamot3@mforebro.se@mforebro.se",
    image: "/styrelsen/Erik-Lagesson.jpg",
  },
  {
    name: "Maja Berlin",
    description: "test4",
    role: "Ledamot",
    mail: "ledamot1@mforebro.se",
    image: "/styrelsen/Maja-Berlin.jpg",
  },
  {
    name: "Johannes Kurt",
    description: "test4",
    role: "Ledamot",
    mail: "ledamot2@mforebro.se",
    image: "/styrelsen/Johannes-Kurt.jpg",
  },
  {
    name: "Harald Lund",
    description: "test4",
    role: "Ledamot",
    mail: "ledamot4@mforebro.se",
    image: "/styrelsen/Harald-Lund.jpg",
  },
  {
    name: "Ella Svegrup",
    description: "test4",
    role: "Utskottsansvarig – Corpus Callosum",
    mail: "Corpuscallosum@mforebro.se",
    image: "/styrelsen/Ella-Svegrup.jpg",
  },
  {
    name: "Sofia Larsson",
    description: "test4",
    role: "Utskottsansvarig – Studiesociala Utskottet",
    mail: "studiesociala@mforebro.se",
    image: "/styrelsen/Sofia-Larsson.jpg",
  },
  {
    name: "Niusha Fzi",
    description: "test4",
    role: "Utskottsansvarig – Kirurgiska Utskottet",
    mail: "kirurgiska@mforebro.se",
    image: "/styrelsen/Niusha-Fzi.jpg",
  },
  {
    name: "Serwan Said",
    description: "test4",
    role: "Utskottsansvarig – Forskningsutskottet",
    mail: "forskningsutskottet@mforebro.se ",
    image: "/styrelsen/Serwan-Said.jpg",
  },
];
