export const styrelsen = [
  {
    name: "Niusha",
    description: "test1",
    role: "Ordförande",
    mail: "ordforande@mforebro.se",
    image: "/styrelsen/Niusha.jpg",
  },
  {
    name: "Hanna",
    description: "test2",
    role: "Vice ordförande",
    mail: "Vice@mforebro.se",
    image: "/styrelsen/Hanna.jpg",
  },
  {
    name: "Ara",
    description: "test3",
    role: "Kassör",
    mail: "",
    image: "/styrelsen/Ara.jpg",
  },
  {
    name: "Wilma",
    description: "test4",
    role: "Medlemsansvarig",
    mail: "info@mforebro.se",
    image: "/styrelsen/Wilma.jpg",
  },
  {
    name: "Ellinor",
    description: "test4",
    role: "Informationsansvarig",
    mail: "info@mforebro.se",
    image: "/styrelsen/Ellinor.jpg",
  },
  {
    name: "Louis",
    description: "test4",
    role: "Ledamot",
    mail: "",
    image: "/styrelsen/Louis.jpg",
  },
  {
    name: "Simon",
    description: "test4",
    role: "Ledamot",
    mail: "",
    image: "/styrelsen/Simon.jpg",
  },
  {
    name: "Filip",
    description: "test4",
    role: "Ledamot",
    mail: "",
    image: "/styrelsen/Filip.jpg",
  },
  {
    name: "Emil",
    description: "test4",
    role: "Ledamot",
    mail: "",
    image: "/styrelsen/Emil.jpg",
  },
  {
    name: "Sofia",
    description: "test4",
    role: "Utskottsansvarig – Idrottsutskottet",
    mail: "idrottsutskottet@mforebro.se",
    image: "/styrelsen/Sofia_Stiernström.jpg",
  },
  {
    name: "Annina",
    description: "test4",
    role: "Utskottsansvarig – Corpus Callosum",
    mail: "corpuscallosum@mforebro.se",
    image: "/styrelsen/Annina.jpg",
  },
  {
    name: "Frida",
    description: "test4",
    role: "Utskottsansvarig – Kirurgiska Utskottet",
    mail: "kirurgiska@mforebro.se ",
    image: "/styrelsen/Frida.jpg",
  },
  {
    name: "Isabelle",
    description: "test4",
    role: "Utskottsansvarig – Studiesociala Utskottet",
    mail: "kirurgiska@mforebro.se ",
    image: "/styrelsen/Isabelle.jpg",
  },
];
